// src/components/ai/AISummary.jsx
// Feature 1: Auto-generates a 3-sentence summary of any post
import { useState } from "react";
import { generateSummary } from "../../ai/aiService";

export default function AISummary({ title, content }) {
  const [summary, setSummary]   = useState("");
  const [loading, setLoading]   = useState(false);
  const [error, setError]       = useState("");
  const [generated, setGenerated] = useState(false);

  const handleGenerate = async () => {
    setLoading(true); setError("");
    try {
      const result = await generateSummary(title, content);
      setSummary(result);
      setGenerated(true);
    } catch (e) {
      setError("Could not generate summary. Please try again.");
    }
    setLoading(false);
  };

  return (
    <div style={s.wrap}>
      {/* Header */}
      <div style={s.header}>
        <div style={s.titleRow}>
          <span style={s.aiIcon}>🤖</span>
          <span style={s.title}>AI Summary</span>
          <span style={s.badge}>Claude AI</span>
        </div>
        {!generated && (
          <button
            style={{ ...s.btn, opacity: loading ? 0.7 : 1 }}
            onClick={handleGenerate}
            disabled={loading}
          >
            {loading ? (
              <><span style={s.spinner} /> Generating…</>
            ) : (
              "✨ Generate Summary"
            )}
          </button>
        )}
        {generated && (
          <button style={s.regenBtn} onClick={handleGenerate} disabled={loading}>
            ↺ Regenerate
          </button>
        )}
      </div>

      {/* Content */}
      {loading && (
        <div style={s.loadingWrap}>
          {[90, 75, 60].map((w, i) => (
            <div key={i} style={{ ...s.skeleton, width: `${w}%`, animationDelay: `${i * 0.15}s` }} />
          ))}
        </div>
      )}

      {summary && !loading && (
        <div style={s.summaryBox}>
          <p style={s.summaryText}>{summary}</p>
          <div style={s.footer}>
            <span style={s.footerText}>✨ Generated by Claude AI</span>
            <button style={s.copyBtn} onClick={() => navigator.clipboard.writeText(summary)}>
              📋 Copy
            </button>
          </div>
        </div>
      )}

      {error && <div style={s.error}>{error}</div>}
    </div>
  );
}

const s = {
  wrap: {
    background: "linear-gradient(135deg, #eff6ff 0%, #f0fdf4 100%)",
    border: "1.5px solid #bfdbfe",
    borderRadius: 14, padding: "20px 22px", marginBottom: 24,
  },
  header: {
    display: "flex", alignItems: "center",
    justifyContent: "space-between", marginBottom: 14, flexWrap: "wrap", gap: 10,
  },
  titleRow: { display: "flex", alignItems: "center", gap: 8 },
  aiIcon: { fontSize: "1.2rem" },
  title: {
    fontFamily: "var(--font-display)", fontWeight: 800,
    fontSize: "0.95rem", color: "var(--ink)",
  },
  badge: {
    fontSize: "0.68rem", fontWeight: 700,
    fontFamily: "var(--font-display)",
    background: "#1d4ed8", color: "#fff",
    padding: "2px 8px", borderRadius: 100,
  },
  btn: {
    padding: "8px 16px", background: "#1d4ed8", color: "#fff",
    border: "none", borderRadius: 8,
    fontFamily: "var(--font-display)", fontWeight: 700, fontSize: "0.82rem",
    cursor: "pointer", display: "flex", alignItems: "center", gap: 6,
    transition: "opacity 0.2s",
  },
  regenBtn: {
    padding: "6px 12px", background: "transparent",
    border: "1px solid #93c5fd", borderRadius: 8,
    fontFamily: "var(--font-display)", fontWeight: 600, fontSize: "0.78rem",
    color: "#1d4ed8", cursor: "pointer",
  },
  spinner: {
    width: 14, height: 14, border: "2px solid rgba(255,255,255,0.3)",
    borderTopColor: "#fff", borderRadius: "50%",
    animation: "spin 0.7s linear infinite", display: "inline-block",
  },
  loadingWrap: { display: "flex", flexDirection: "column", gap: 8 },
  skeleton: {
    height: 14, borderRadius: 6,
    background: "linear-gradient(90deg, #dbeafe 25%, #bfdbfe 50%, #dbeafe 75%)",
    backgroundSize: "400px 100%",
    animation: "shimmer 1.4s ease infinite",
  },
  summaryBox: {
    background: "#fff", borderRadius: 10,
    padding: "14px 16px", border: "1px solid #bfdbfe",
  },
  summaryText: {
    fontSize: "0.95rem", lineHeight: 1.78,
    color: "#1e3a5f", fontFamily: "var(--font-body)",
  },
  footer: {
    display: "flex", alignItems: "center",
    justifyContent: "space-between", marginTop: 12,
  },
  footerText: {
    fontSize: "0.72rem", color: "#60a5fa",
    fontFamily: "var(--font-display)", fontWeight: 600,
  },
  copyBtn: {
    padding: "4px 10px", background: "transparent",
    border: "1px solid #bfdbfe", borderRadius: 6,
    fontSize: "0.72rem", fontFamily: "var(--font-display)",
    fontWeight: 600, color: "#1d4ed8", cursor: "pointer",
  },
  error: {
    background: "#fee2e2", color: "#dc2626", borderRadius: 8,
    padding: "10px 14px", fontSize: "0.83rem",
    fontFamily: "var(--font-display)", fontWeight: 600,
  },
};